kind: pipeline
type: docker
name: docker-zandronum-server
steps:
  - name: build-and-publish
    image: plugins/docker
    settings:
      username:
        from_secret: ci_registry_user
      password:
        from_secret: ci_registry_password
      repo:
        from_secret: ci_registry_image
